name: Deploy using AWS SSM Send-Command

on:
  push:
    branches: [main]

jobs:
  start:
    runs-on: [self-hosted, ubuntu-22.04]

    steps:
      - name: AWS SSM Send Command
        uses: peterkimzz/aws-ssm-send-command@master
        with:
          aws-region: us-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          instance-ids: ${{ secrets.INSTANCE_ID  }}
          comment: Deploy the main branch
          working-directory: /home/ubuntu/casper-dex-frontend
          command: git pull
          comment: Git Pull
